### ISSUE TITLE
Add hovers with transition to all interactive elements

### ISSUE THREAD

**Issue by rudnitskih** [anastasiia-emets/bicycle-landing#10]
![image](https://user-images.githubusercontent.com/8848858/50549072-63f5f280-0c5f-11e9-9b71-33997e7bc51d.png)

**Comment by rudnitskih** [comment]
![image](https://user-images.githubusercontent.com/8848858/50549082-75d79580-0c5f-11e9-88d0-abd256a693fc.png)

**Comment by rudnitskih** [comment]
![image](https://user-images.githubusercontent.com/8848858/50549087-7bcd7680-0c5f-11e9-81ac-315042116a29.png)

**Comment by rudnitskih** [comment]
Don't forget about transitions! It does your site more cool!

**Comment by anastasiia-emets** [comment]
please tell me about transitions? what exactly?it's not just a hover effect, which change color?

**Comment by rudnitskih** [comment]
Color or opacity is ok, I mean `transition: color .2s`. It will add smooth changes to elements.

**Comment by rudnitskih** [comment]
Additional issue:
![image](https://user-images.githubusercontent.com/8848858/50678408-3914f100-1007-11e9-96a4-d5c4734ac5d2.png)
