### ISSUE TITLE
Not clear steps

### ISSUE THREAD

**Issue by rudnitskih** [anastasiia-emets/bicycle-landing#2]
What exactly commands I need to run in the console to run your project? Please format code examples in readme like this - `gulp start`. Why do you use prefix "gulp $" in "gulp $ npx gulp"? 
![image](https://user-images.githubusercontent.com/8848858/50548843-2f346c00-0c5c-11e9-9e87-3c8394af344c.png)

**Comment by anastasiia-emets** [comment]
![image](https://user-images.githubusercontent.com/40547968/50606930-23e97680-0ed0-11e9-913f-580fdc85c17b.png)
It's right?

**Comment by rudnitskih** [comment]
Amazing!
