### ISSUE TITLE
Adjust grid to different screens  

### ISSUE THREAD

**Issue by rudnitskih** [anastasiia-emets/bicycle-landing#3]
![image](https://user-images.githubusercontent.com/8848858/50548931-68b9a700-0c5d-11e9-8fa2-13d0ff9d37f0.png)

**Comment by anastasiia-emets** [comment]
![image](https://user-images.githubusercontent.com/40547968/50613097-1ab6d480-0ee5-11e9-8d2b-f2dbabc9cc8b.png)
