### ISSUE TITLE
Saving image as SVG doesn't mean it is real vector graphic 

### ISSUE THREAD

**Issue by rudnitskih** [anastasiia-emets/bicycle-landing#5]
Actually, all your svg images are just jpeg inside svg container 

![image](https://user-images.githubusercontent.com/8848858/50548950-b1716000-0c5d-11e9-9f2b-a86aa4ec6f1c.png)

**Comment by anastasiia-emets** [comment]
so what to do in this case? i took svg from adobe.

**Comment by rudnitskih** [comment]
I recommend finding social icons SVG in Internet. If Adobe doesn't export real SVG for images just export 2x png files and use them.

**Comment by anastasiia-emets** [comment]
![image](https://user-images.githubusercontent.com/40547968/50729093-847ceb80-113c-11e9-8703-badf66ad5e6b.png)
