### ISSUE TITLE
Remove automatically generated and unneeded files from src

### ISSUE THREAD

**Issue by rudnitskih** [anastasiia-emets/bicycle-landing#6]
![image](https://user-images.githubusercontent.com/8848858/50548974-f4cbce80-0c5d-11e9-940b-f01d5645c8cb.png)

**Comment by anastasiia-emets** [comment]
![image](https://user-images.githubusercontent.com/40547968/50608063-01595c80-0ed4-11e9-86c5-16a42773e596.png)

**Comment by rudnitskih** [comment]
why you have `lib/OwlCarousel` and `owlcarousel` directories?

**Comment by anastasiia-emets** [comment]
![image](https://user-images.githubusercontent.com/40547968/50728123-c05c8480-112d-11e9-857f-a5e51ef62c3d.png)
