### ISSUE TITLE
Improve last two blocks on mobile  

### ISSUE THREAD

**Issue by rudnitskih** [anastasiia-emets/bicycle-landing#7]
![image](https://user-images.githubusercontent.com/8848858/50549000-5ab85600-0c5e-11e9-8f2c-525ae1c1af9b.png)

**Comment by anastasiia-emets** [comment]
![image](https://user-images.githubusercontent.com/40547968/50611572-9e6dc280-0edf-11e9-903b-dcb4b68e45f9.png)
