### ISSUE TITLE
Wrong BEM usage

### ISSUE THREAD

**Issue by rudnitskih** [anastasiia-emets/bicycle-landing#8]
You have block `header`. Inside element `header__linki`. What is `header__linki_link`? According to BEM methodology: `header__linki_link` is element `header__linki` with modificator `link`. But I think you meant another - you have an additional element in this block.

Correct name `header__link`.

Fix all other similuar places.

![image](https://user-images.githubusercontent.com/8848858/50549038-dadebb80-0c5e-11e9-9e99-9dfce332c2a4.png)

**Comment by anastasiia-emets** [comment]
![image](https://user-images.githubusercontent.com/40547968/50608887-9e1cf980-0ed6-11e9-8bd6-d9fe591820e5.png)

**Comment by rudnitskih** [comment]
What is `header__link_photo`? Is it a link with additional modification for the logo, so the class should be `header__link header__link_photo`. If link and logo doesn't have common properties, so class should be `header__logo`

**Comment by rudnitskih** [comment]
Fix other similar places in the project not only in a header.
