### ISSUE TITLE
White lines in the gallery 

### ISSUE THREAD

**Issue by rudnitskih** [anastasiia-emets/bicycle-landing#9]
Stretch all images to their container - use `height: 100%, object-fit: cover`

![image](https://user-images.githubusercontent.com/8848858/50549059-2b561900-0c5f-11e9-9f47-da05b6d8cf11.png)

**Comment by anastasiia-emets** [comment]
![image](https://user-images.githubusercontent.com/40547968/50609567-c148a880-0ed8-11e9-9a17-f1d94eecf752.png)
